name: Deploy Python App to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build and run Gunicorn
      run: |
        gunicorn -b 0.0.0.0:8000 -w 3 -t 60 app:app
    - name: Start Celery beat
      run: |
        celery -A worker beat --loglevel=info
      env:
        REDIS_URL: ${{ secrets.REDIS_URL }}

    - name: Start Celery worker
      run: |
        celery -A worker worker --loglevel=info
      env:
        REDIS_URL: ${{ secrets.REDIS_URL }}

    - name: Deploy to GitHub Pages
      run: |
        git config user.name "${{ secrets.GITHUB_ACTOR }}"
        git config user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
        git clone --branch=gh-pages https://github.com/yourusername/your-repo.git deploy
        rsync -avz --delete your_app/static/ deploy/
        cd deploy
        git add .
        git commit -m "GitHub Pages deploy by GitHub Actions"
        git push origin gh-pages
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      API_URL: ${{ secrets.API_URL }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
